org: shubhammishra
app: hello-world-offline-app
service: hello-world-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: default
  # memorySize: 256 # optional, in MB, default is 1024
  stage: dev

plugins:
  - serverless-offline

functions:
  contact:
    handler: handler.contact # required, handler set in AWS Lambda
    # name: "${self:service}-${self:provider.stage}" # optional, Deployed Lambda name
    description: "slspress offline example"
    events:
      - http:
          path: contact
          method: get
          cors: true
